name: Release
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  general-build-release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        # language=Bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm ci

      - name: Build and Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODOIST_CLIENT_ID: ${{ secrets.TODOIST_CLIENT_ID }}
          TODOIST_CLIENT_SECRET: ${{ secrets.TODOIST_CLIENT_SECRET }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          releaseDraft: true
          prerelease: false
          tagName: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
          releaseName: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
          releaseBody: "See the assets to download this version and install."
          generateReleaseNotes: true

      - name: Debug - List Files
        run: ls -R src-tauri/target/release/bundle

      - name: Upload Deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capturist_${{ github.ref_type == 'tag' && github.ref_name || 'build' }}_amd64.deb
          path: src-tauri/target/release/bundle/deb/Capturist_*_amd64.deb

  snap-build:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build.outputs.snap }}
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        # language=Bash
        run: |
          echo "TODOIST_CLIENT_ID=${{ secrets.TODOIST_CLIENT_ID }}" > .env
          echo "TODOIST_CLIENT_SECRET=${{ secrets.TODOIST_CLIENT_SECRET }}" >> .env

      - name: Build Snap
        id: build
        uses: snapcore/action-build@v1

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap-artifact
          path: ${{ steps.build.outputs.snap }}

  snap-release:
    permissions:
      contents: write
    needs:
      - general-build-release
      - snap-build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Snap artifact
        uses: actions/download-artifact@v4
        with:
          name: snap-artifact
          path: .

      - name: Publish Snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ needs.snap-build.outputs.snap-file }}
          release: ${{ github.ref_type == 'tag' && 'stable' || 'edge' }}

      - name: Upload Snap to Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          make_latest: false
          files: "*.snap"
          fail_on_unmatched_files: true
          append_body: true

  flatpak-build:
    needs: general-build-release
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Download Deb Artifact
        uses: actions/download-artifact@v4
        with:
          name: capturist_${{ github.ref_type == 'tag' && github.ref_name || 'build' }}_amd64.deb
          path: .

      - name: Rename Deb for Manifest
        run: mv Capturist_*.deb distribution/flatpak/capturist.deb

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: capturist.flatpak
          manifest-path: distribution/flatpak/me.ariyadey.capturist.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Upload Flatpak Bundle to Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          make_latest: false
          files: "capturist.flatpak"
          fail_on_unmatched_files: true
          append_body: true
